name: hello-world

on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print a message from file
        run: echo "$(cat hello_world.txt)"

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies and build
        run: npm install && npm run build

